export const demoReels = [
  {
    id: 'demo-reel-1',
    title: 'DenceWance न्यूज़रूम: डिजिटल जर्नलिज़्म का भविष्य',
    slug: 'demo-reel-bjmc-newsroom',
    caption: 'डिजिटल वर्कफ्लो, रियल टाइम फैक्ट चेक और मल्टी-पर्सपेक्टिव स्टोरी मैप्स।',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    cover_image_url: 'https://images.unsplash.com/photo-1523240795612-9a054b0db644?q=80&w=1200&auto=format&fit=crop',
    creator_name: 'DenceWance न्यूज़',
    creator_handle: 'dencewancenews',
    creator_avatar: '',
    tags: ['BJMC', 'न्यूज़रूम', 'डिजिटल'],
    status: 'published',
    is_active: true,
    is_demo_creator: true,
    views: 924,
    likes: 88,
    shares: 14,
    published_at: '2026-02-15T10:30:00.000Z',
  },
  {
    id: 'demo-reel-2',
    title: 'मीडिया टेक्नोलॉजी: XR और इमर्सिव रिपोर्टिंग',
    slug: 'demo-reel-xr-reporting',
    caption: 'XR आधारित इमर्सिव स्टोरीटेलिंग — बीजेएमसी का नया अध्याय।',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    cover_image_url: 'https://images.unsplash.com/photo-1518770660439-4636190af475?q=80&w=1200&auto=format&fit=crop',
    creator_name: 'DenceWance टेक',
    creator_handle: 'dencewancetech',
    creator_avatar: '',
    tags: ['XR', 'इमर्सिव', 'रिपोर्टिंग'],
    status: 'published',
    is_active: true,
    is_demo_creator: true,
    views: 712,
    likes: 65,
    shares: 9,
    published_at: '2026-02-12T08:15:00.000Z',
  },
  {
    id: 'demo-reel-3',
    title: 'डेटा जर्नलिज़्म: लोकल इशू ट्रैकर डेमो',
    slug: 'demo-reel-data-desk',
    caption: 'वार्ड-स्तर की समस्याओं को मैप करने वाला ओपन डैशबोर्ड।',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    cover_image_url: 'https://images.unsplash.com/photo-1504384308090-c894fdcc538d?q=80&w=1200&auto=format&fit=crop',
    creator_name: 'DenceWance डेटा',
    creator_handle: 'dencewancedata',
    creator_avatar: '',
    tags: ['डेटा', 'डैशबोर्ड', 'जर्नलिज़्म'],
    status: 'published',
    is_active: true,
    is_demo_creator: true,
    views: 452,
    likes: 38,
    shares: 10,
    published_at: '2026-02-10T12:00:00.000Z',
  },
  {
    id: 'demo-reel-4',
    title: 'स्टूडेंट इनोवेशन फेयर: न्यूज़ ऑटोमेशन शोकेस',
    slug: 'demo-reel-innovation-fair',
    caption: '100+ प्रोजेक्ट्स, मीडिया-टेक और उन्नत प्रोटोटाइप्स।',
    video_url: 'https://commondatastorage.googleapis.com/gtv-videos-bucket/sample/ForBiggerBlazes.mp4',
    cover_image_url: 'https://images.unsplash.com/photo-1517248135467-4c7edcad34c4?q=80&w=1200&auto=format&fit=crop',
    creator_name: 'DenceWance इवेंट्स',
    creator_handle: 'dencewanceevents',
    creator_avatar: '',
    tags: ['इवेंट', 'इनोवेशन', 'BJMC'],
    status: 'published',
    is_active: true,
    is_demo_creator: true,
    views: 367,
    likes: 31,
    shares: 5,
    published_at: '2026-02-09T09:40:00.000Z',
  },
];